# LibraryBuild.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: LibraryBuild
on:
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.hpp'
    - '**LibraryBuild.yml'
  pull_request:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.hpp'
    - '**LibraryBuild.yml'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.

    env:
      # Comma separated list without double quotes around the list.
      REQUIRED_LIBRARIES: Servo,ServoEasing,IRremote,NeoPatterns,Adafruit NeoPixel,PlayRtttl

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
        #############################################################################################################
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:uno|USE_PARALLEL_1602_LCD
          - arduino:avr:uno|USE_SERIAL_2004_LCD

        # Specify parameters for each board.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            required-libraries: LiquidCrystal

          - arduino-boards-fqbn: arduino:avr:uno|USE_PARALLEL_1602_LCD
            required-libraries: LiquidCrystal
            build-properties:
              All: -DUSE_PARALLEL_1602_LCD

          - arduino-boards-fqbn: arduino:avr:uno|USE_SERIAL_2004_LCD
            required-libraries: LiquidCrystal I2C
            build-properties:
              All: -DUSE_SERIAL_2004_LCD

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          required-libraries: ${{ matrix.required-libraries }}
          build-properties: ${{ toJson(matrix.build-properties) }}